[package]
name = "sonic-search"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.101"
clap = { version = "4.5.58", features = ["derive"] }
fuzzy-matcher = "0.3.7"
ignore = "0.4.25"
rayon = "1.11.0"
